#mysql
spring:
  profiles:
    active: #springActive#
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    http:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/teacserplat?useUnicode=true&characterEncoding=utf8
    username: root
    password:
#tomcat
server:
  tomcat:
    uri-encoding: UTF-8
      max-threads: 1000
      min-spare-threads: 30
      port: 8080