#mysql

spring:

  profiles:

    active: #springActive#
  jpa:
    hibernate:
    ddl-auto: create
    show-sql: true
    open-in-view: false
  # jackson时间格式化

  jackson:

    time-zone: GMT+8

    date-format: yyyy-MM-dd HH:mm:ss

    http:

      multipart:

        max-file-size: 100MB

        max-request-size: 100MB

        enabled: true

  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://127.0.0.1:3306/teacserplat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8

    username: root

    password: root

#tomcat

server:

  tomcat:

    uri-encoding: UTF-8

    port: 8080

mybatis:

  mapperLocations: classpath:mapper/*.xml

  typeAliasesPackage: com.faculty.interadmin.entity

